# Generated by Django 3.1.7 on 2021-06-26 18:32

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=100, null=True)),
                ('Address', models.CharField(max_length=100, null=True)),
                ('emil', models.CharField(max_length=100, null=True)),
                ('dob', models.CharField(max_length=100, null=True)),
                ('id_proof', models.ImageField(null=True, upload_to='', verbose_name='images/')),
                ('place', models.CharField(max_length=100, null=True)),
                ('district', models.CharField(max_length=100, null=True)),
                ('nation', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Facility', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotelss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Image', models.ImageField(null=True, upload_to='', verbose_name='images/')),
                ('Place', models.CharField(max_length=100, null=True)),
                ('Status', models.CharField(max_length=100, null=True)),
                ('status1', models.CharField(default='0', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact', models.CharField(max_length=100, null=True)),
                ('Address', models.CharField(max_length=100, null=True)),
                ('Emil', models.CharField(max_length=100, null=True)),
                ('Dob', models.CharField(max_length=100, null=True)),
                ('Id_proof', models.ImageField(null=True, upload_to='', verbose_name='images/')),
                ('Place', models.CharField(max_length=100, null=True)),
                ('District', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('Userr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_app.hotelss')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomtype', models.CharField(max_length=100, null=True)),
                ('Details', models.CharField(max_length=100, null=True)),
                ('images', models.ImageField(null=True, upload_to='', verbose_name='image/')),
                ('status', models.CharField(max_length=100, null=True)),
                ('Hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_app.hotelss')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.CharField(max_length=100, null=True)),
                ('total', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('HOTEL', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_app.hotelss')),
                ('roomtype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_app.roomtype')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.CharField(max_length=100, null=True)),
                ('check_in_date', models.CharField(max_length=100, null=True)),
                ('check_out_time', models.CharField(max_length=100, null=True)),
                ('check_out_date', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('manager', models.CharField(max_length=100, null=True)),
                ('status1', models.CharField(max_length=100, null=True)),
                ('Customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_app.customer')),
                ('ROOM', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_app.rooms')),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('Customers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_app.customer')),
                ('MANAGER', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_app.manager')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_app.rooms')),
                ('userr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='facilityselected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statuss', models.CharField(max_length=100, null=True)),
                ('facilityy', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), default=list, null=True, size=10)),
                ('Reserve', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_app.reservation')),
                ('Users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
