# Generated by Django 3.1.7 on 2021-06-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
