# Generated by Django 3.1.7 on 2021-06-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_reservation_status2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status2',
            field=models.CharField(default='null', max_length=100, null=True),
        ),
    ]
